Repository Pebblz/FindersKeepers, pull requests merged in 2021-02, with the labels that each got.

#2 Feedback button
  Assets/Prefabs/Flicker SpotLight.prefab
  Assets/Prefabs/Flicker SpotLight.prefab.meta
  Assets/Prefabs/GameManager.prefab
  Assets/Prefabs/GameManager.prefab.meta
  Assets/Prefabs/air_vent.fbx
  Assets/Prefabs/air_vent.fbx.meta
  Assets/Prefabs/map.fbx
  Assets/Prefabs/map.fbx.meta
  Assets/Prefabs/proptest.fbx
  Assets/Prefabs/proptest.fbx.meta
  Assets/Prefabs/proptest2.fbx
  Assets/Prefabs/proptest2.fbx.meta
  Assets/Prefabs/proptest3.fbx
  Assets/Prefabs/proptest3.fbx.meta
  Assets/Prefabs/room.fbx
  Assets/Prefabs/room.fbx.meta
  Assets/Scenes/Launcher.unity
  Assets/Scripts/Launcher.cs
  Assets/Scripts/Places.cs
  Assets/Scripts/Places.cs.meta
  Assets/UI/LondrinaSolid-Black.ttf
  Assets/UI/LondrinaSolid-Black.ttf.meta
  Assets/UI/feedback.png
  Assets/UI/feedback.png.meta
Labels: enhancement

#5 Brandons god gamer branch
  Assets/Character.controller
  Assets/Scenes/Lobby_1.unity
  Assets/Scenes/Lobby_2.unity
  Assets/Scenes/Lobby_2.unity.meta
  Assets/Scenes/Lobby_3.unity
  Assets/Scenes/Lobby_3.unity.meta
  Assets/Scenes/Lobby_4.unity
  Assets/Scenes/Lobby_4.unity.meta
  Assets/Scripts/PickUpAbles.cs
  Assets/Scripts/PlayerPickUp.cs
  Assets/Scripts/Player_Movement.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: bug, enhancement

#7 Update Timer.cs
  Assets/Scripts/Timer.cs
Labels: documentation, enhancement

#8 fixed player loading
  Assets/Scripts/GameManager.cs
Labels: bug

#9 Fix player disconnect
  Assets/Scenes/Main Game.unity
  Assets/Scripts/GameManager.cs
Labels: bug

#6 Pat refactoring
  Assets/Scenes/Main Game.unity
  Assets/Scenes/WinOrLose.unity
  Assets/Scripts/CreditSceneScript.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Launcher.cs
  Assets/Scripts/RoomRandomizer.cs
  Assets/Scripts/TodoList.cs
  Assets/Scripts/WinOrLoseScript.cs
  Assets/UI/1st.renderTexture
  Assets/UI/1st.renderTexture.meta
  Assets/UI/2nd.renderTexture
  Assets/UI/2nd.renderTexture.meta
  Assets/UI/3rd.renderTexture
  Assets/UI/3rd.renderTexture.meta
  Assets/UI/4th.renderTexture
  Assets/UI/4th.renderTexture.meta
Labels: documentation, enhancement, question

#22 Todo list adjustment
  Assets/Resources/BilliardsRoomPrefab.prefab
  Assets/Resources/DiningRoomPrefab.prefab
  Assets/Resources/KitchenPrefab.prefab
  Assets/Resources/LibraryPrefab.prefab
  Assets/Resources/LivingRoomPrefab.prefab
  Assets/Resources/MusicRoomPrefab.prefab
  Assets/Resources/StorageRoomPrefab.prefab
  Assets/Scripts/TodoList.cs
  Assets/prop renders/Library bookshelf.png
  Assets/prop renders/Library bookshelf.png.meta
  Assets/prop renders/WIP statue.png
  Assets/prop renders/WIP statue.png.meta
  Assets/prop renders/bathroom rug.png
  Assets/prop renders/bathroom rug.png.meta
  Assets/prop renders/easle.png
  Assets/prop renders/easle.png.meta
  Assets/prop renders/hamper.png
  Assets/prop renders/hamper.png.meta
  Assets/prop renders/living room sofa.png
  Assets/prop renders/living room sofa.png.meta
  Assets/prop renders/pot.png
  Assets/prop renders/pot.png.meta
  Assets/prop renders/skeleton sitting.png
  Assets/prop renders/skeleton sitting.png.meta
  Assets/prop renders/storage chair.png
  Assets/prop renders/storage chair.png.meta
  Assets/prop renders/study chair.png
  Assets/prop renders/study chair.png.meta
  Assets/prop renders/study lamp.png
  Assets/prop renders/study lamp.png.meta
Labels: bug, enhancement

#32 Reorganizing my scripts pat
  Assets/New Folder.meta
  Assets/Scripts/Buttons.meta
  Assets/Scripts/InGameUI.meta
  Assets/Scripts/InGameUI/Places.cs
  Assets/Scripts/InGameUI/Places.cs.meta
  Assets/Scripts/InGameUI/Timer.cs
  Assets/Scripts/InGameUI/Timer.cs.meta
  Assets/Scripts/InGameUI/TodoList.cs
  Assets/Scripts/InGameUI/TodoList.cs.meta
  Assets/Scripts/Player_Movement.cs.meta
  Assets/Scripts/WinOrLoseScript.cs
Labels: documentation

#44 Fixed teleportation glitch
  Assets/Scripts/GameManager.cs
  Assets/Scripts/Player_Movement.cs
Labels: bug

#28 Yo ug ot to ma ke ab ra nc h
  Assets/Scenes/Main Game.unity
  Assets/Scenes/WinOrLose.unity
  Assets/Scripts/WinOrLoseScript.cs
Labels: bug

#56 Better soundtrack
  Assets/MUSIC_SFX/AnticipatedChaos-Intro.wav.meta
  Assets/MUSIC_SFX/AnticipatedChaos-Song.wav.meta
  Assets/MUSIC_SFX/Lobby Music Final.wav.meta
  Assets/MUSIC_SFX/Lobby.wav.meta
  Assets/MUSIC_SFX/LobbyNoTail-002.wav.meta
  Assets/Resources/BackgroundMusic.prefab
  Assets/Resources/BackgroundMusic.prefab.meta
  Assets/Resources/PlayerSounds.mixer
  Assets/Resources/PlayerSounds.mixer.meta
  Assets/Resources/Players/Blue_Mann.prefab
  Assets/Resources/Players/Green_Mann.prefab
  Assets/Resources/Players/Purp_Mann.prefab
  Assets/Resources/Players/Red_Mann.prefab
  Assets/Resources/Players/YellowB_Mann.prefab
  Assets/Resources/Players/YellowW_Mann.prefab
  Assets/Resources/SoundManager.prefab
  Assets/Resources/SoundManager.prefab.meta
  Assets/Scenes/Josh.unity
  Assets/Scenes/Lobby_1.unity
  Assets/Scenes/Lobby_2.unity
  Assets/Scenes/Lobby_3.unity
  Assets/Scenes/Lobby_4.unity
  Assets/Scenes/Main Game.unity
  Assets/Scenes/WinOrLose.unity
  Assets/Scripts/DropOffZoneScript.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/NetworkCodes.cs
  Assets/Scripts/Player.cs
  Assets/Scripts/PlayerPickUp.cs
  Assets/Scripts/Player_Movement.cs
  Assets/Scripts/SoundManager.cs
  Assets/Scripts/SoundManager.cs.meta
  Assets/Scripts/SoundtrackManager.cs
  Assets/Scripts/SoundtrackManager.cs.meta
  ProjectSettings/TagManager.asset
Labels: bug, enhancement

#63 Fix net 4 real
  Assets/Scenes/Launcher.unity
  Assets/Scripts/GameManager.cs
  Assets/Scripts/InGameUI/Places.cs
  Assets/Scripts/Launcher.cs
  Assets/Scripts/PickUpAbles.cs
Labels: bug, enhancement

#67 Win and lose update
  Assets/Resources/SoundManager.prefab
  Assets/Scenes/WinOrLose.unity
  Assets/Scripts/GameManager.cs
  Assets/Scripts/InGameUI/Button_Script.cs
  Assets/Scripts/InGameUI/Button_Script.cs.meta
  Assets/Scripts/NetworkCodes.cs
  Assets/Scripts/Player.cs
  Assets/Scripts/PlayerPickUp.cs
  Assets/Scripts/SoundManager.cs.meta
  Assets/Scripts/WinOrLoseScript.cs
Labels: bug

#69 Fix music
  Assets/Scripts/PlayerPickUp.cs
  Assets/Scripts/SoundManager.cs
Labels: bug

#70 Make code upper
  Assets/Scenes/Launcher.unity
  Assets/Scripts/Launcher.cs
Labels: enhancement

#72 Fix camera
  Assets/Resources/Players/Black_Mann.prefab
  Assets/Resources/Players/Blue_Mann.prefab
  Assets/Resources/Players/Brown_Mann.prefab
  Assets/Resources/Players/Cyan_Mann.prefab
  Assets/Resources/Players/DGreen_Mann.prefab
  Assets/Resources/Players/DPurp_Mann.prefab
  Assets/Resources/Players/DRed_Mann.prefab
  Assets/Resources/Players/Green_Mann.prefab
  Assets/Resources/Players/LBlue_Mann.prefab
  Assets/Resources/Players/LGray_Mann.prefab
  Assets/Resources/Players/Mung_Mann.prefab
  Assets/Resources/Players/Orange_Mann.prefab
  Assets/Resources/Players/Pink_Mann.prefab
  Assets/Resources/Players/Purp_Mann.prefab
  Assets/Resources/Players/Red_Mann.prefab
  Assets/Resources/Players/Salmon_Mann.prefab
  Assets/Resources/Players/Tan_Mann.prefab
  Assets/Resources/Players/YellowB_Mann.prefab
  Assets/Resources/Players/YellowW_Mann.prefab
  Assets/Scripts/Player.cs
Labels: bug
